from .cooperative_persona import COOPERATIVE_PERSONA_PROMPT, ORGANIZATION_PERSONA_PROMPT
from .domain_prompts import (
    COMUNICACION_SOCIAL_PROMPT,
    DESARROLLO_TECNICO_PROMPT,
    FINANZAS_SOLIDARIAS_PROMPT,
    LEGAL_SOCIAL_PROMPT,
    SECRETARIA_ASAMBLEA_PROMPT,
    SPECIALIST_DESCRIPTIONS,
    VIGILANCIA_PROMPT,
)
from .grant_procurement import GRANT_PROCUREMENT_PROMPT

__all__ = [
    "COOPERATIVE_PERSONA_PROMPT",
    "ORGANIZATION_PERSONA_PROMPT",
    "GRANT_PROCUREMENT_PROMPT",
    "VIGILANCIA_PROMPT",
    "LEGAL_SOCIAL_PROMPT",
    "FINANZAS_SOLIDARIAS_PROMPT",
    "DESARROLLO_TECNICO_PROMPT",
    "COMUNICACION_SOCIAL_PROMPT",
    "SECRETARIA_ASAMBLEA_PROMPT",
    "SPECIALIST_DESCRIPTIONS",
]
